#include "commands.h"

const struct command commands[] = {
    { "help",       "[command]",            "Show commands, or help for one command", cmd_help },
    { "echo",       "[-n] [text...]",       "Print text", cmd_echo },
    { "exit",       "[status]",             "Log out", cmd_exit },
    { "logout",     "",                     "Log out", cmd_exit },
    { "clear",      "",                     "Clear the screen", cmd_clear },
    { "history",    "",                     "Show command history", cmd_history },
    { "env",        "",                     "Show environment variables", cmd_env },
    { "export",     "NAME=VALUE...",        "Set environment variables", cmd_export },
    { "whoami",     "",                     "Show the current user", cmd_whoami },
    { "id",         "",                     "Show user and group IDs", cmd_id },
    { "date",       "",                     "Show the date and time (UTC)", cmd_date },
    { "uptime",     "",                     "Show time since boot", cmd_uptime },
    { "uname",      "[-a]",                 "Show system information", cmd_uname },
    { "kill",       "[-SIGNAL] PID...",     "Send a signal (default TERM) to processes", cmd_kill },
    { "sleep",      "SECONDS",              "Wait", cmd_sleep },
    { "sudo",       "COMMAND [args...]",    "Run a command as root", cmd_sudo },
    { "run",        "PROGRAM [args...]",    "Run a program (also: type its name or path)", cmd_run },
    { "cd",         "[DIR]",                "Change directory (default: home, -: previous)", cmd_cd },
    { "pwd",        "",                     "Print the current directory", cmd_pwd },
    { "ls",         "[-la] [PATH...]",      "List directory contents", cmd_ls },
    { "cat",        "[FILE...]",            "Print files (or standard input)", cmd_cat },
    { "mkdir",      "[-p] DIR...",          "Create directories", cmd_mkdir },
    { "rmdir",      "DIR...",               "Remove empty directories", cmd_rmdir },
    { "rm",         "[-rf] PATH...",        "Remove files or directories", cmd_rm },
    { "cp",         "[-r] SRC... DEST",     "Copy files or directories", cmd_cp },
    { "mv",         "SRC... DEST",          "Move or rename", cmd_mv },
    { "touch",      "FILE...",              "Create files or update their times", cmd_touch },
    { "chmod",      "MODE PATH...",         "Change permissions (octal MODE)", cmd_chmod },
    { "chown",      "USER[:GROUP] PATH...", "Change owner and group", cmd_chown },
    { "ln",         "[-s] TARGET LINK",     "Create a hard or symbolic link", cmd_ln },
    { "stat",       "PATH...",              "Show file details", cmd_stat },
    { "df",         "[PATH...]",            "Show free disk space", cmd_df },
    { "sync",       "",                     "Write pending changes to disk", cmd_sync },
    { "reboot",     "",                     "Restart the machine (root)", cmd_reboot },
    { "shutdown",   "",                     "Power off the machine (root)", cmd_shutdown },
    { "resolution", "WIDTHxHEIGHT",         "Change the display resolution (root)", cmd_resolution },
};

const size_t command_count = sizeof(commands) / sizeof(commands[0]);
