#include "commands.h"

const struct command commands[] = {
    { "help",       "[command]",            "Show commands, or help for one command", cmd_help },
    { "echo",       "[-n] [text...]",       "Print text", cmd_echo },
    { "exit",       "[status]",             "Sign out", cmd_exit },
    { "signout",    "",                     "Sign out", cmd_exit },
    { "clear",      "",                     "Clear the screen", cmd_clear },
    { "history",    "",                     "Show command history", cmd_history },
    { "vars",       "",                     "Show variables", cmd_env },
    { "set",        "NAME=VALUE...",        "Set variables (passed to programs)", cmd_export },
    { "me",         "",                     "Show who you are", cmd_whoami },
    { "ids",        "",                     "Show your account and group numbers", cmd_id },
    { "date",       "",                     "Show the date and time (UTC)", cmd_date },
    { "uptime",     "",                     "Show time since startup", cmd_uptime },
    { "system",     "[-a]",                 "Show system information", cmd_uname },
    { "tasks",      "[-a]",                 "Show running threads (-a: everyone's)", cmd_tasks },
    { "stop",       "[-SIGNAL] ID...",      "Send a signal (default TERM) to threads", cmd_kill },
    { "wait",       "SECONDS",              "Wait", cmd_sleep },
    { "elevate",    "COMMAND [args...]",    "Run a command as the superuser", cmd_sudo },
    { "run",        "PROGRAM [args...]",    "Run a program (also: type its name or path)", cmd_run },
    { "go",         "[FOLDER]",             "Change folder (default: home, -: previous)", cmd_cd },
    { "where",      "",                     "Show the current folder", cmd_pwd },
    { "list",       "[-la] [PATH...]",      "List what is in folders", cmd_ls },
    { "show",       "[FILE...]",            "Print files (or standard input)", cmd_cat },
    { "find",       "[-ivnc] TEXT [FILE...]", "Print lines containing TEXT", cmd_grep },
    { "newfolder",  "[-p] FOLDER...",       "Create folders", cmd_mkdir },
    { "newfile",    "FILE...",              "Create files or update their times", cmd_touch },
    { "delete",     "[-rf] PATH...",        "Delete files or folders (-r: with what is inside)", cmd_rm },
    { "copy",       "[-r] SRC... DEST",     "Copy files or folders", cmd_cp },
    { "move",       "SRC... DEST",          "Move or rename", cmd_mv },
    { "access",     "MODE PATH...",         "Change who may read, write and run (octal MODE)", cmd_chmod },
    { "owner",      "USER[:GROUP] PATH...", "Change owner and group", cmd_chown },
    { "link",       "[-s] TARGET LINK",     "Create a link", cmd_ln },
    { "details",    "PATH...",              "Show file details", cmd_stat },
    { "space",      "[PATH...]",            "Show free disk space", cmd_df },
    { "flush",      "",                     "Write pending changes to disk", cmd_sync },
    { "restart",    "[--firmware]",         "Restart, or into UEFI setup (superuser)", cmd_reboot },
    { "shutdown",   "",                     "Power off (superuser)", cmd_shutdown },
    { "crash",      "",                     "Stop with the crash screen, to test it (superuser)", cmd_crash },
    { "resolution", "WIDTHxHEIGHT",         "Change the display resolution (superuser)", cmd_resolution },
};

const size_t command_count = sizeof(commands) / sizeof(commands[0]);

// Names people may type from other systems, and what they are called here.
const struct renamed_command renamed_commands[] = {
    { "ls", "list" },       { "dir", "list" },      { "cat", "show" },      { "type", "show" },
    { "cd", "go" },         { "pwd", "where" },     { "cp", "copy" },       { "mv", "move" },
    { "rm", "delete" },     { "rmdir", "delete" },  { "del", "delete" },    { "mkdir", "newfolder" },
    { "md", "newfolder" },  { "touch", "newfile" }, { "grep", "find" },     { "ps", "tasks" },
    { "kill", "stop" },     { "sudo", "elevate" },  { "su", "elevate" },    { "whoami", "me" },
    { "id", "ids" },        { "uname", "system" },  { "env", "vars" },      { "export", "set" },
    { "sleep", "wait" },    { "chmod", "access" },  { "chown", "owner" },   { "ln", "link" },
    { "stat", "details" },  { "df", "space" },      { "sync", "flush" },    { "reboot", "restart" },
    { "logout", "signout" }, { "dmesg", "klog" },   { "ifconfig", "network" }, { "crontab", "routines" },
    { "sha256sum", "checksum" }, { "nc", "connect" }, { "bash", "terminal" }, { "sh", "terminal" },
    { NULL, NULL },
};
